GET http://localhost:3003/api/blogs/

###
GET http://localhost:3003/api/blogs/2

###
GET http://localhost:3003/api/blogs/6978b198fd2a0a0daf0a512d

###
DELETE http://localhost:3003/api/blogs/697a0f966aa8008a778e2b41

###
POST http://localhost:3003/api/blogs
Content-Type: application/json

{
    "title": "Vasya's blog",
    "author": "Vasya Pupkin",
    "url": "",
    "likes": 2
}

###
POST http://localhost:3003/api/blogs
Content-Type: application/json

{
    "title": "Petya's blog",
    "author": "Petya",
    "url": "",
    "likes": 252
}

###
POST http://localhost:3003/api/blogs
Content-Type: application/json

{
    "title": "Olivia's blog",
    "author": "Olivia Reinert",
    "url": "",
    "likes": 1024
}
