GET http://localhost:3003/api/blogs/

###
GET http://localhost:3003/api/blogs/2

###
GET http://localhost:3003/api/blogs/6981cb9b686a58dc03707b3d

###
DELETE http://localhost:3003/api/blogs/6981cb9b686a58dc03707b3d

###
POST http://localhost:3003/api/blogs
Content-Type: application/json

{
    "title": "Vasya's blog",
    "author": "Vasya Pupkin",
    "url": "",
    "likes": 2
}

###
POST http://localhost:3003/api/blogs
Content-Type: application/json

{
    "title": "Petya's blog",
    "author": "Petya",
    "url": "",
    "likes": 252
}

###
POST http://localhost:3003/api/blogs
Content-Type: application/json

{
    "title": "Anna's blog",
    "author": "h",
    "url": "",
    "likes": 2228
}
